---
- name: Aeron Deployment
  hosts: all
  become: true
  vars:
    hyperthreading: false
    aeron_version: "1.44.1"
    java_version: "21"
    aeron_dir: "/opt/aeron"
    
  roles:
    - role: aeron-install
      tags: [install, aeron]
    - role: aeron-benchmark
      tags: [benchmark]
